// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#if UI_ENABLE_TACHOMETER_SCREEN


#include "../ui.h"



	
void ui_tach_screen_screen_init(void)
{
    ui_tach_screen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tach_screen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_tach_screen, lv_color_hex(0xffffff), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_tach_screen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
	
	ui_tach_gauge = lv_meter_create(ui_tach_screen);
    lv_obj_center(ui_tach_gauge);
    lv_obj_set_size(ui_tach_gauge, 300, 300);	
	lv_obj_set_style_bg_color(ui_tach_gauge, lv_color_hex(0x121212), LV_STATE_DEFAULT);
	lv_obj_set_style_border_color(ui_tach_gauge, lv_color_hex(0x121212), LV_STATE_DEFAULT);
	
    /*Add a scale first*/
    lv_meter_scale_t* scale = lv_meter_add_scale(ui_tach_gauge);
    lv_meter_set_scale_ticks(ui_tach_gauge, scale, 41, 2, 10, lv_color_hex(0xfafafa));
    lv_meter_set_scale_major_ticks(ui_tach_gauge, scale, 5, 8, 25, lv_color_hex(0xfafafa), 20);
    lv_meter_set_scale_range(ui_tach_gauge, scale, 0, 8, 270, 90);
	lv_obj_set_style_text_font(ui_tach_gauge, &lv_font_montserrat_26, LV_STATE_DEFAULT);
	lv_obj_set_style_text_color(ui_tach_gauge, lv_color_hex(0xfafafa), LV_STATE_DEFAULT);

	lv_meter_scale_t* hidden_scale = lv_meter_add_scale(ui_tach_gauge);
	lv_meter_set_scale_ticks(ui_tach_gauge, hidden_scale, 101, 0, 0, lv_color_hex(0x0000ff));
	lv_meter_set_scale_range(ui_tach_gauge, hidden_scale, 0, 101, 270, 90);

    lv_meter_indicator_t * indic;

	/*Add a white arc to the whole thing*/
    indic = lv_meter_add_arc(ui_tach_gauge, scale, 2, lv_color_hex(0xfafafa), 0);
    lv_meter_set_indicator_start_value(ui_tach_gauge, indic, 0);
    lv_meter_set_indicator_end_value(ui_tach_gauge, indic, 6);
	

    /*Add a red arc to the end*/
    indic = lv_meter_add_arc(ui_tach_gauge, scale, 6, lv_color_hex(0xdb1616), 0);
    lv_meter_set_indicator_start_value(ui_tach_gauge, indic, 6);
    lv_meter_set_indicator_end_value(ui_tach_gauge, indic, 8);

    /*Make the tick lines red at the end of the scale*/
    indic = lv_meter_add_scale_lines(ui_tach_gauge, scale, lv_color_hex(0xdb1616), lv_color_hex(0xdb1616), false, 0);
    lv_meter_set_indicator_start_value(ui_tach_gauge, indic, 6);
    lv_meter_set_indicator_end_value(ui_tach_gauge, indic, 8);

    /*Add a needle line indicator*/
    indic = lv_meter_add_needle_line(ui_tach_gauge, hidden_scale, 5, lv_color_hex(0xdb1616), -10);//lv_meter_add_needle_img(ui_tach, hidden_scale, &Gauge_needle, 30, 17); 
	lv_meter_set_indicator_value(ui_tach_gauge, indic, 27);
	lv_obj_set_style_height(ui_tach_gauge, 25, LV_PART_INDICATOR);
	lv_obj_set_style_width(ui_tach_gauge, 25, LV_PART_INDICATOR);
	lv_obj_set_style_shadow_color(ui_tach_gauge, lv_color_hex(0xdb1616), LV_PART_INDICATOR);
	lv_obj_set_style_shadow_width(ui_tach_gauge, 10, LV_PART_INDICATOR);
	
	/*Add the RPM label.*/
	lv_obj_t* ui_tach_rpm_lbl = lv_label_create(ui_tach_gauge);
	lv_obj_align(ui_tach_rpm_lbl, LV_ALIGN_CENTER, 50, 50);
	lv_obj_set_style_text_align(ui_tach_rpm_lbl, LV_ALIGN_LEFT_MID, LV_STATE_DEFAULT);
	lv_label_set_text(ui_tach_rpm_lbl, "RPM\nx1000");
	lv_obj_set_style_text_color(ui_tach_rpm_lbl, lv_color_hex(0xfafafa), LV_STATE_DEFAULT);
	lv_obj_set_style_text_font(ui_tach_rpm_lbl, &lv_font_montserrat_14, LV_STATE_DEFAULT);
	
	
// 	/*Create an animation to set the value*/
//     lv_anim_t a;
//     lv_anim_init(&a);
//     lv_anim_set_exec_cb(&a, ui_tach_set_value_animation);
//     lv_anim_set_var(&a, indic);
//     lv_anim_set_values(&a, 0, 100);
//     lv_anim_set_time(&a, 2000);
//     lv_anim_set_repeat_delay(&a, 100);
//     lv_anim_set_playback_time(&a, 500);
//     lv_anim_set_playback_delay(&a, 100);
//     lv_anim_set_repeat_count(&a, LV_ANIM_REPEAT_INFINITE);
//     lv_anim_start(&a);
}


#endif //UI_ENABLE_TACHOMETER_SCREEN
