/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32h745xx.h"

#include "system/system_cm4.h"

#include "touch_screen/cst830_touch_cm4.h"
#include "application/app_can_get_baud_rate_cm4.h"
#include "application/app_can_sniffer_cm4.h"

#include "FreeRTOS.h"
#include <task.h>
#include <queue.h>
#include <list.h>
#include <semphr.h>

int main(void)
{
	system_task_init();

	/*
	 * Updates the touch screen data. Needs to be high priority, runs quick and the latency of
	 * the touch screen relies on it.
	 * */
	xTaskCreate(cst830_update, "CST830_UPDATE", 1024, NULL, 3, NULL);

	/*Gets CAN baud rates, triggered by HSEM 0.*/
	xTaskCreate(app_can_baud_rate_run, "APP_GET_BAUD_RATE", 1000, NULL, 2, &sys_task_handle_app_get_baud_rate);
	vTaskSuspend(sys_task_handle_app_get_baud_rate);

	/*Monitors the HSEMs for a signal from CM7 to run something.*/
	xTaskCreate(system_task_monitor, "SYS_MONITOR", 500, NULL, 3, NULL);

	/*Handles incoming CAN data. Can be blocking and must be low priority.*/
	xTaskCreate(app_can_sniffer_run, "CAN_SNIFFER", 1500, NULL, 1, app_can_sniffer_task_handle);

	vTaskStartScheduler();

}
